#!/usr/bin/env bash

set -e

echo "---"
echo "--- Running all unit tests"
echo "---"

for x in */Makefile; do
    cd $(dirname $x)
    echo "=== Entering $PWD"
    make clean
    make run
    echo "=== Exiting $PWD"
    cd ..
done
    
echo "==="
echo "=== Unit tests passed"
echo "==="
