#!/usr/bin/env python

import os
import os.path
import re
import sys

include = os.path.join(os.path.dirname(os.path.realpath(__file__)), '..', 'include')
educc_home=os.path.join(os.path.dirname(os.path.realpath(__file__)), '..', 'educc')
cu2cpp=os.path.join(educc_home, 'cu2cpp', 'educc-cu2cpp')
ast=os.path.join(educc_home, 'ast', 'educc-ast')
cxx='g++'

path_in = sys.argv[1]
path_gen_cu2cpp = os.path.join(os.path.dirname(path_in), '.' + os.path.basename(path_in) + "-cu2cpp.cpp")
path_gen_ast = os.path.join(os.path.dirname(path_in), '.' + os.path.basename(path_in) + "-ast.cpp")
path_bin = os.path.splitext(path_in)[0]

def shell(cmd):
	rc = os.system(cmd)
	if rc != 0:
		sys.exit(1)

shell(cu2cpp + ' ' + path_in + ' > ' + path_gen_cu2cpp)
shell(ast + ' ' + path_gen_cu2cpp + ' > ' + path_gen_ast)
shell(cxx + ' -I' + include + ' -std=c++11 -fopenmp -g -o ' + path_bin + ' ' + path_gen_ast + ' -lpthread')
